#                                     $input                  $output  isREAL  isPbPb
#root -b -l -q 'MakeDsMinTree.C++ ("Ds_phikkpi_pt4.root" ,"test.root", 0 ,0)'



root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt22_f0980kkpi_pt0.root" ,"output/DsMinTree_PbPb_MC_NonPrompt22_f0980kkpi_pt0.root", 0 ,1)'  
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt22_f0980kkpi_pt19.root" ,"output/DsMinTree_PbPb_MC_NonPrompt22_f0980kkpi_pt19.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt22_f0980kkpi_pt1p8.root" ,"output/DsMinTree_PbPb_MC_NonPrompt22_f0980kkpi_pt1p8.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt22_f0980kkpi_pt3p8.root" ,"output/DsMinTree_PbPb_MC_NonPrompt22_f0980kkpi_pt3p8.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt22_f0980kkpi_pt5p7.root" ,"output/DsMinTree_PbPb_MC_NonPrompt22_f0980kkpi_pt5p7.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt22_f0980kkpi_pt9p5.root" ,"output/DsMinTree_PbPb_MC_NonPrompt22_f0980kkpi_pt9p5.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt_phikkpi_pt0.root" ,"output/DsMinTree_PbPb_MC_NonPrompt_phikkpi_pt0.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt_phikkpi_pt19.root" ,"output/DsMinTree_PbPb_MC_NonPrompt_phikkpi_pt19.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt_phikkpi_pt1p8.root" ,"output/DsMinTree_PbPb_MC_NonPrompt_phikkpi_pt1p8.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt_phikkpi_pt3p8.root" ,"output/DsMinTree_PbPb_MC_NonPrompt_phikkpi_pt3p8.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt_phikkpi_pt5p7.root" ,"output/DsMinTree_PbPb_MC_NonPrompt_phikkpi_pt5p7.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_NonPrompt_phikkpi_pt9p5.root" ,"output/DsMinTree_PbPb_MC_NonPrompt_phikkpi_pt9p5.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_f0980kkpi_pt0.root" ,"output/DsMinTree_PbPb_MC_Prompt_f0980kkpi_pt0.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_f0980kkpi_pt19.root" ,"output/DsMinTree_PbPb_MC_Prompt_f0980kkpi_pt19.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_f0980kkpi_pt1p8.root" ,"output/DsMinTree_PbPb_MC_Prompt_f0980kkpi_pt1p8.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_f0980kkpi_pt3p8.root" ,"output/DsMinTree_PbPb_MC_Prompt_f0980kkpi_pt3p8.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_f0980kkpi_pt5p7.root" ,"output/DsMinTree_PbPb_MC_Prompt_f0980kkpi_pt5p7.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_f0980kkpi_pt9p5.root" ,"output/DsMinTree_PbPb_MC_Prompt_f0980kkpi_pt9p5.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_phikkpi_pt0.root" ,"output/DsMinTree_PbPb_MC_Prompt_phikkpi_pt0.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_phikkpi_pt19.root" ,"output/DsMinTree_PbPb_MC_Prompt_phikkpi_pt19.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_phikkpi_pt1p8.root" ,"output/DsMinTree_PbPb_MC_Prompt_phikkpi_pt1p8.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_phikkpi_pt3p8.root" ,"output/DsMinTree_PbPb_MC_Prompt_phikkpi_pt3p8.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_phikkpi_pt5p7.root" ,"output/DsMinTree_PbPb_MC_Prompt_phikkpi_pt5p7.root", 0 ,1)'
root -b -l -q 'MakeDsMinTree.C++ ("/scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/PbPb_MC/Dntuple_PbPb_MC_Prompt_phikkpi_pt9p5.root" ,"output/DsMinTree_PbPb_MC_Prompt_phikkpi_pt9p5.root", 0 ,1)'
