ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_Phi_pt0/*.root >      Ds_PbPb_MC_NonPrompt_Phi_pt0.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_Phi_pt10/*.root >     Ds_PbPb_MC_NonPrompt_Phi_pt10.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_Phi_pt19/*.root >     Ds_PbPb_MC_NonPrompt_Phi_pt19.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_Phi_pt2/*.root >      Ds_PbPb_MC_NonPrompt_Phi_pt2.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_Phi_pt4/*.root >      Ds_PbPb_MC_NonPrompt_Phi_pt4.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_Phi_pt6/*.root >      Ds_PbPb_MC_NonPrompt_Phi_pt6.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_f0_pt0/*.root >       Ds_PbPb_MC_NonPrompt_f0_pt0.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_f0_pt10/*.root >      Ds_PbPb_MC_NonPrompt_f0_pt10.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_f0_pt19/*.root >      Ds_PbPb_MC_NonPrompt_f0_pt19.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_f0_pt2/*.root >       Ds_PbPb_MC_NonPrompt_f0_pt2.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_f0_pt4/*.root >       Ds_PbPb_MC_NonPrompt_f0_pt4.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_NonPrompt_f0_pt6/*.root >       Ds_PbPb_MC_NonPrompt_f0_pt6.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_Phi_pt0/*.root >         Ds_PbPb_MC_Prompt_Phi_pt0.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_Phi_pt10/*.root >        Ds_PbPb_MC_Prompt_Phi_pt10.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_Phi_pt19/*.root >        Ds_PbPb_MC_Prompt_Phi_pt19.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_Phi_pt2/*.root >         Ds_PbPb_MC_Prompt_Phi_pt2.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_Phi_pt4/*.root >         Ds_PbPb_MC_Prompt_Phi_pt4.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_Phi_pt6/*.root >         Ds_PbPb_MC_Prompt_Phi_pt6.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_f0_pt0/*.root >          Ds_PbPb_MC_Prompt_f0_pt0.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_f0_pt10/*.root >         Ds_PbPb_MC_Prompt_f0_pt10.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_f0_pt19/*.root >         Ds_PbPb_MC_Prompt_f0_pt19.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_f0_pt2/*.root >          Ds_PbPb_MC_Prompt_f0_pt2.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_f0_pt4/*.root >          Ds_PbPb_MC_Prompt_f0_pt4.lis
ls /scratch/halstead/p/peng43/Ds_phikkpi/Dntuple/offPbPb_MC/Ds_PbPb_MC_Prompt_f0_pt6/*.root >          Ds_PbPb_MC_Prompt_f0_pt6.lis      

